name: PR Analysis Workflow

on:
  pull_request:
    types: [opened, synchronize, closed]

permissions:
  pull-requests: write

jobs:
  cost-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Call FastAPI Webhook for Cost Analysis
        id: cost_analysis
        run: |
          API_URL="http://your-fastapi-server.com/webhook"
          RESPONSE=$(curl -X POST "$API_URL" -H "Content-Type: application/json" -d '{
            "repo_url": "${{ github.event.pull_request.head.repo.clone_url }}",
            "pr_number": "${{ github.event.pull_request.number }}",
            "pr_url": "${{ github.event.pull_request.html_url }}",
            "pr_title": "${{ github.event.pull_request.title }}",
            "pr_author": "${{ github.event.pull_request.user.login }}",
            "pr_status": "${{ github.event.pull_request.state }}"
          }')

          echo "API_RESPONSE=$(echo "$RESPONSE" | jq -c)" >> $GITHUB_ENV

      - name: Parse JSON and Post Comments
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          echo "$API_RESPONSE" | jq -c '.results | to_entries[]' | while read -r line; do
            FILE_PATH=$(echo "$line" | jq -r '.key')
            TITLE=$(echo "$line" | jq -r '.value.title')
            COST_ANALYSIS=$(echo "$line" | jq -r '.value.cost_analysis')

            COMMENT_BODY="**Cost Analysis Result for \`$FILE_PATH\`**\n\n"
            COMMENT_BODY+="<details>\n"
            COMMENT_BODY+="<summary> $TITLE </summary>\n\n"
            COMMENT_BODY+="$COST_ANALYSIS\n\n"
            COMMENT_BODY+="</details>"
            
            curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              -d "{\"body\": \"$COMMENT_BODY\"}" \
              "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/issues/$PR_NUMBER/comments"
          done



          




